### ISSUE TITLE
cdc.js handshake fail

### ISSUE THREAD

**Issue by niciqy** [pcon/SalesforceApps#20]
Hi am trying out the cdc example, more specifically, `cdc.js`. I keep getting handshake fail and just couldn't get it working

Error:
`
{ id: '1',
  successful: false,
  channel: '/meta/handshake',
  failure:
   { websocketCode: 1000,
     reason: 'Error',
     connectionType: 'websocket',
     transport: { envelopes: {}, timeouts: {}, webSocket: [WebSocket] },
     message:
      { id: '1',
        version: '1.0',
        minimumVersion: '1.0',
        channel: '/meta/handshake',
        supportedConnectionTypes: [Array],
        advice: [Object] } } }
`

**Comment by pcon** [comment]
@niciqy it was working at one point.  I don't know why it's not working now.  I took a little bit of time to dive into the [JSforce Streaming code](https://jsforce.github.io/jsforce/doc/api_streaming.js.html) and found that they will support the CDC topics if you pass them in.  So I've added a new [cdc_jsforce.js](https://github.com/pcon/SalesforceApps/blob/master/cdc_example/cdc_jsforce.js) example that does it without having to use the other cometd library.  I'm going to leave the old one up just as an example, but I'd say that using jsforce's streaming implementation is better and it has the added benefit of updating the API version whenever you update the package.
